//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Stats.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class F1StatsDatabaseEntities : DbContext
    {
        public F1StatsDatabaseEntities()
            : base("name=F1StatsDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Csapat> Csapat { get; set; }
        public virtual DbSet<Eredmeny> Eredmeny { get; set; }
        public virtual DbSet<Versenyhetvege> Versenyhetvege { get; set; }
        public virtual DbSet<Versenyzo> Versenyzo { get; set; }
    }
}
