//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Stats.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Versenyhetvege
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Versenyhetvege()
        {
            this.Eredmeny = new HashSet<Eredmeny>();
        }
    
        public string nev { get; set; }
        public int VERSENYHETVEGE_SZAMA { get; set; }
        public int hossz { get; set; }
        public int kor { get; set; }
        public System.DateTime idopont { get; set; }
        public string helyszin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eredmeny> Eredmeny { get; set; }
    }
}
