//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Stats.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Versenyzo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Versenyzo()
        {
            this.Eredmeny = new HashSet<Eredmeny>();
        }
    
        public int rajtszam { get; set; }
        public string nev { get; set; }
        public string csapat_nev { get; set; }
        public int eletkor { get; set; }
        public Nullable<int> ossz_pont { get; set; }
        public Nullable<int> idenybeli_pont { get; set; }
    
        public virtual Csapat Csapat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eredmeny> Eredmeny { get; set; }
    }
}
